### PR TITLE
docs: noticed a couple of issues with documentable edge cases

### PR DESCRIPTION
**Pull request by alexmiddeleer**

### CODE REVIEW

**Comment by alexmiddeleer** [comment]
Essentially, things did not act as expected when I ran `buttle --watch **/*`--I needed quotes around the pattern.  Also, I was slightly surprised when my totally empty html file did not successfully live-reload, though it's not really worth fixing imo.

**Comment by jtrussell** [comment]
Huh. I can't reproduce the need for quotes around the watch pattern but I've definitely run into situations before where it didn't feel like the pattern was being honored. Any chance the file you were hoping would be watched was created after you kicked off `buttle -w **/*`? In any event it won't hurt anything to have those in there so I'm cool with adding it if it ends up helping anyone. Also, you're totally right about the `html`/`body` tag being necessary. Thanks!

**Comment by alexmiddeleer** [comment]
@jtrussell Nope, I restarted buttle a bunch of times--it was driving me slightly crazy actually, because it had seemed to work beautifully at first. I wonder if the shell was being weird in some way.

**Comment by jtrussell** [comment]
I suspect there's either something funky with the modules I'm using for live reloading or (more likely) the way I implemented it. If you can get something reproducible let me know.

**Pull request merged**
